/// <reference lib="webworker" />
import { precacheAndRoute } from 'workbox-precaching';

declare let self: ServiceWorkerGlobalScope;

// Precache the assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Handle Push Events (if integrated with a real server later)
self.addEventListener('push', (event) => {
  let data = { title: 'Al-Barakah Reminder', body: 'Please log your recent sales.' };
  if (event.data) {
    try {
      data = event.data.json();
    } catch (e) {
      data.body = event.data.text();
    }
  }

  const options: NotificationOptions = {
    body: data.body,
    icon: '/icon.svg',
    badge: '/icon.svg',
    // @ts-ignore
    vibrate: [200, 100, 200],
    data: {
      dateOfArrival: Date.now(),
      primaryKey: '1'
    }
  };

  event.waitUntil(
    self.registration.showNotification(data.title, options)
  );
});

// Notification Click Handler
self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  event.waitUntil(
    self.clients.matchAll({ type: 'window' }).then((clientList) => {
      for (const client of clientList) {
        if (client.url === '/' && 'focus' in client) {
          return client.focus();
        }
      }
      if (self.clients.openWindow) {
        return self.clients.openWindow('/');
      }
    })
  );
});

// Periodic Background Sync (works on supported browsers when PWA is installed)
self.addEventListener('periodicsync', (event: any) => {
  if (event.tag === 'check-reminders') {
    event.waitUntil(
      (async () => {
        // Fallback generic message
        let body = 'Did you forget to add any recent sales or expenses? Please log your transactions.';
        
        // We can access IndexedDB directly from Service Worker to check borrowings
        try {
          const req = indexedDB.open('AlBarakahDB');
          await new Promise((resolve, reject) => {
            req.onsuccess = (e: any) => {
              const db = e.target.result;
              if (!db.objectStoreNames.contains('borrowings')) {
                resolve(null);
                return;
              }
              const tx = db.transaction('borrowings', 'readonly');
              const store = tx.objectStore('borrowings');
              const getAllReq = store.getAll();
              
              getAllReq.onsuccess = () => {
                const borrowings = getAllReq.result;
                let overdueTotal = 0;
                const nowTimeDate = new Date();
                
                borrowings.forEach((b: any) => {
                  if (b.status !== 'Paid') {
                    const dueTime = new Date(b.dueDate);
                    if (dueTime < nowTimeDate && dueTime.toDateString() !== nowTimeDate.toDateString()) {
                      overdueTotal += (b.amount - b.paidAmount);
                    }
                  }
                });
                
                if (overdueTotal > 0) {
                  body = `WARNING: You have Tk ${overdueTotal.toLocaleString()} in OVERDUE borrowings! Please pay your lenders.`;
                }
                resolve(null);
              };
              getAllReq.onerror = () => resolve(null);
            };
            req.onerror = () => resolve(null);
          });
        } catch (err) {
          console.warn('Could not read DB in service worker', err);
        }

        return (self.registration.showNotification as any)('Al-Barakah Reminder', {
          body,
          icon: '/icon.svg',
          badge: '/icon.svg',
          vibrate: [200, 100, 200]
        });
      })()
    );
  }
});
